### PR TITLE
Fix preloaded pool size

### PR DESCRIPTION
**Pull request by bokobza**

### CODE REVIEW

**Comment by frol** [comment]
@bokobza Yeah, thanks for clarifying it in the original PR. This is the least intrusive change, but to make it completely nice, I suggest to introduce the `blocks_preload_pool_size` as additional parameter:

```python
def __init__(…, preload_pool_size=None, blocks_preload_pool_size=200):
    self.blocks_preload_pool_size = blocks_preload_pool_size
    # Legacy compatibility to avoid breaking changes
    if preload_pool_size is not None:
        self.blocks_preload_pool_size = preload_pool_size
```

What do you think?

@race-of-sloths invite

**Comment by race-of-sloths** [comment]
@frol Thank you for calling!
    
@bokobza Thank you for the contribution! Join [Race of Sloths](https://race-of-sloths.com) by simply mentioning me in your comment/PRs description and start collecting Sloth Points through contributions to open source projects.

<details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/bokobza)

For maintainers:
- Score pull requests that participate in the Race of Sloths and receive a reward
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by bokobza** [comment]
I think it's better to do without the 
```python
# Legacy compatibility to avoid breaking changes
    if preload_pool_size is not None:
        self.blocks_preload_pool_size = preload_pool_size
```

Let me lay all the options out.

### With my changes:
If a user was calling it like this:
```python
 LakeConfig(
            network=self.network,
            start_block_height=starting_block_height,
            aws_access_key_id=aws_access_key_id,
            aws_secret_key=aws_secret_key
        )
```
the blocks pool size will be 200 as before, and if the user was calling it like this:

```python
 LakeConfig(
            network=self.network,
            start_block_height=starting_block_height,
            aws_access_key_id=aws_access_key_id,
            aws_secret_key=aws_secret_key,
            preload_pool_size=75
        )
```
the blocks pool size will become 75. IT's fixed, but if the user was relying on this working as it should and they're happy with the 200 blocks they're getting, then I agree this may introduce an unwelcomed change.

### With your change:
If a user was calling it like this:
```python
 LakeConfig(
            network=self.network,
            start_block_height=starting_block_height,
            aws_access_key_id=aws_access_key_id,
            aws_secret_key=aws_secret_key
        )
```
the blocks pool size will be 200 as before, and if the user was calling it like this:

```python
 LakeConfig(
            network=self.network,
            start_block_height=starting_block_height,
            aws_access_key_id=aws_access_key_id,
            aws_secret_key=aws_secret_key,
            preload_pool_size=75
        )
```
the blocks pool size will become 75, which is exactly the same as my change.

So in a nutshell, it's exactly the same, the only difference is that with your changes, we end up with 2 similar parameters.

### better solution

```python
def __init__(…, preload_pool_size=None, blocks_preload_pool_size=200):
    self.blocks_preload_pool_size = blocks_preload_pool_size
   ...  
```

with this changes:
If a user was calling it like this:
```python
 LakeConfig(
            network=self.network,
            start_block_height=starting_block_height,
            aws_access_key_id=aws_access_key_id,
            aws_secret_key=aws_secret_key
        )
```
the blocks pool size will be 200 as before, and if the user was calling it like this:

```python
 LakeConfig(
            network=self.network,
            start_block_height=starting_block_height,
            aws_access_key_id=aws_access_key_id,
            aws_secret_key=aws_secret_key,
            preload_pool_size=75
        )
```
the blocks pool size will still be 200, like it was before.
Then, the only way to specify the blocks pool size will be to do
```python
 LakeConfig(
            network=self.network,
            start_block_height=starting_block_height,
            aws_access_key_id=aws_access_key_id,
            aws_secret_key=aws_secret_key,
            preload_pool_size=75,
            blocks_preload_pool_size= 100
        )
```

**Comment by frol** [comment]
@bokobza should we then warn users at runtime that preload_pool_size is noop?

**Comment by bokobza** [comment]
We could add a warning log that says "The preload_pool_size argument is not used and will be deprecated in a future release. Use blocks_preload_pool_size instead."

**Comment by bokobza** [comment]
@frol @frolvanya I think this is ready for review now.

**Review by frolvanya — APPROVED** [review]

**Comment by frolvanya** [comment]
@bokobza Thanks for your contribution!

**Comment by frolvanya** [comment]
I've updated pypi package: https://pypi.org/project/near-lake-framework/0.1.2/

**Pull request merged**
